metadata:
  slug: aws-eks
  name: AWS EKS
  description: Start, run, and scale Kubernetes applications in the AWS cloud and on-premises data centers.
  categories: ['Infrastructure']
  logoUrlDark: https://nh-addons.s3.us-east-1.amazonaws.com/aws-eks/logo-dark.png
  logoUrlLight: https://nh-addons.s3.us-east-1.amazonaws.com/aws-eks/logo-light.png
  detailUrl: https://addons.kaops.net/aws-eks/
  externalUrl: https://aws.amazon.com/pm/eks/
  isProduction: false
  installTargets:
    hub: true
    hubRequired: true
    edge: false

forms: 
  - slug: default
    label: AWS EKS configuration
    description: Start, run, and scale Kubernetes applications in the AWS cloud and on-premises data centers.
variables:
  - slug: 'providerConfigRef'
    path: 'providerConfigRef'
    forms: ['default']
    ui:
      type: 'cloudProvider'
      label: 'Provider Config Name'
      validation: 'required'
  - slug: 'clusterName'
    path: 'tf.clusterName'
    forms: ['default']
    ui:
      type: 'text'
      label: 'EKS Cluster Name'
      validation: 'required'
  - slug: 'region'
    path: 'tf.region'
    forms: ['default']
    ui:
      type: 'text'
      label: 'AWS Region'
  - slug: 'instanceTypeDefault'
    path: 'tf.instanceTypeDefault'
    forms: ['default']
    ui:
      type: 'text'
      label: 'AWS Instance Type for a default node group'
  - slug: 'instanceTypeGpu'
    path: 'tf.instanceTypeGpu'
    forms: ['default']
    ui:
      type: 'text'
      label: 'AWS Instance Type for a GPU node group'
  - slug: 'amiType'
    path: 'tf.amiType'
    forms: ['default']
    ui:
      type: 'text'
      label: 'AMI Type for a GPU node group'
  - slug: 'vpcCidr'
    path: 'tf.vpcCidr'
    forms: ['default']
    ui:
      type: 'text'
      label: 'Value of the VPC CIDR'
system: